#!/bin/sh

set -e

SITE="$1"

cd "$SITE"
touch .nojekyll
git init
git add .
git -c user.name='travis' -c user.email='travis' commit -m "Deploy for $TRAVIS_COMMIT"
# Make sure to make the output quiet, or else the API token will leak!
# This works because the API key can replace your password.
if [ -n "$GITHUB_API_KEY" ]; then
    git push \
      --set-upstream \
      --force \
      --quiet \
      https://sergiusens:$GITHUB_API_KEY@github.com/sergiusens/sergiusens.github.com.git master &2>/dev/null
else
    git push \
      --set-upstream \
      --force \
      https://github.com/sergiusens/sergiusens.github.com.git master &2>/dev/null
fi
